branch-defaults:
  main:
    environment: eb-ts-express-dev
    group_suffix: null
deploy:
  artifact: artifacts/eb-ts-express.zip
global:
  application_name: eb-ts-express
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli.aeweb
  repository: null
  sc: git
  workspace_type: Application
